### PR TITLE
feat: add renderItem

### PR DESCRIPTION
**Pull request by demedos**
Adds the `renderItem` method, which can be used to display a custom element instead of children.
This is extremely useful for having a custom trigger element, e.g. a button above an image, and is fully backward compatible.

It also fixes the typescript return types of the `renderHeader` and `renderContent` methods, which should return a JSX.Element instead of void.

https://user-images.githubusercontent.com/16702156/153588340-954f4820-2c3b-4d6d-8dbb-7ca48ec77940.mov

### CODE REVIEW

**Comment by cbbfcd** [comment]
I have been a little busy recently, sorry, I will review all the codes in the past two days, and I will continue to invest in improving this project in the future, thank you~ @demedos

**Comment by cbbfcd** [comment]
> This branch has conflicts that must be resolved

@demedos 😂

**Comment by demedos** [comment]
Hi @cbbfcd , I know that this conflicts with master, but this is supposed to be a v0.9.0 based off the current npm release which is v0.8.8

**Comment by demedos** [comment]
It would be great if you could create a branch from the v0.8.8 tag and merge the PRs (this, https://github.com/cbbfcd/react-native-lightbox/pull/5 and https://github.com/cbbfcd/react-native-lightbox/pull/6) to create a v0.9.0 (a minor because the API changes) and release it to npm 😉

**Comment by cbbfcd** [comment]
@demedos If you have time, can you make a new PR based on 0.9.0? thx~

**Comment by demedos** [comment]
yeah sure, I'll do this in the next few days

**Comment by demedos** [comment]
I'm sorry but I just noticed that https://github.com/cbbfcd/react-native-lightbox/pull/5 and https://github.com/cbbfcd/react-native-lightbox/pull/6 has ported into master rather than being created as a new tag starting off v0.8.9. master seems to be a complete rewrite with many changes and API improvements, but it is not retro compatible. Mind creating a new release based off v0.8.9? You can add me as a contributor if you want help with that

**Comment by cbbfcd** [comment]
What if it is implemented directly based on the current master code? 👀

**Comment by alessioemireni** [comment]
+1

**Pull request closed without merging**
